export const packageEntries = Object.freeze({
  main: 'src/index.ts',
  'provider-registration': 'src/provider-registration.ts',
  'openai/index': 'src/openai/index.ts',
  'llm/providers.eager': 'src/llm/providers.eager.ts',
  'llm/openai/index': 'src/llm/openai/index.ts',
  'llm/mistral/index': 'src/llm/mistral/index.ts',
  'llm/anthropic/index': 'src/llm/anthropic/index.ts',
  'llm/google/index': 'src/llm/google/index.ts',
  'llm/bedrock/index': 'src/llm/bedrock/index.ts',
  'llm/vertexai/index': 'src/llm/vertexai/index.ts',
  'llm/openrouter/index': 'src/llm/openrouter/index.ts',
  'responses/index': 'src/responses/index.ts',
  'langchain/index': 'src/langchain/index.ts',
  'langchain/google-common': 'src/langchain/google-common.ts',
  'langchain/language_models/chat_models':
    'src/langchain/language_models/chat_models.ts',
  'langchain/messages': 'src/langchain/messages.ts',
  'langchain/messages/tool': 'src/langchain/messages/tool.ts',
  'langchain/openai': 'src/langchain/openai.ts',
  'langchain/prompts': 'src/langchain/prompts.ts',
  'langchain/runnables': 'src/langchain/runnables.ts',
  'langchain/tools': 'src/langchain/tools.ts',
  'langchain/utils/env': 'src/langchain/utils/env.ts',
});
